x1, y1, x2, y2, x3, y3, x4, y4 = map(float,input("nhập các giá trị:").split())
M = (x1, y1)
N = (x2, y2)
P = (x3, y3)
Q = (x4, y4)
MN = ( (x1+x2)/2 , (y1+y2)/2)
NP = ( (x2+x3)/2 , (y2+y3)/2)
PQ = ( (x3+x4)/2 , (y3+y4)/2)
QM = ( (x4+x1)/2 , (y4+y1)/2)
print("tọa độ trung điểm của cạnh MN là:",MN)
print("tọa độ trung điểm của cạnh NP là:",NP)
print("tọa độ trung điểm của cạnh PQ là:",PQ)
print("tọa độ trung điểm của cạnh QM là:",QM)